name: CI Unit Test on PR to Main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Jar
        run: mvn package -DskipTests -f $GITHUB_WORKSPACE/reservation-service/pom.xml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.ECR_PUBLISHER_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.ECR_PUBLISHER_SECRET_ACCESS_KEY_ID}}
          aws-region: ${{secrets.ECR_REGION}}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
